// The served visualizer page: a minimal HTML shell around the stage-1 page
// bundle (see page/main.js). PAGE_JS is generated by esbuild.js and spliced in
// at build time, so its content (backticks and all) never has to survive TS
// template-literal escaping. The full stylesheet lives in the bundle
// (page/style.js) so the demo harness renders identically; the inline style
// below only pins the background before the script runs (no white flash in
// dark mode).

import { PAGE_JS } from "./generated/pageBundle";

export const PAGE: string =
  "<!doctype html>\n" +
  '<html lang="en">\n' +
  "<head>\n" +
  '<meta charset="utf-8" />\n' +
  '<meta name="viewport" content="width=device-width, initial-scale=1" />\n' +
  "<title>Graphify</title>\n" +
  "<style>\n" +
  "  :root { color-scheme: light dark; }\n" +
  "  html, body { margin: 0; height: 100%; background: #f8f9fb; }\n" +
  "  @media (prefers-color-scheme: dark) { html, body { background: #0f1117; } }\n" +
  "</style>\n" +
  "</head>\n" +
  "<body>\n" +
  '<div id="app"></div>\n' +
  "<script>\n" +
  PAGE_JS +
  "\n</script>\n" +
  "</body>\n" +
  "</html>\n";
